INSERT INTO "PostTypes" ("Id", "Name")
VALUES (1, 'Question'),
       (2, 'Answer'),
       (3, 'Orphaned tag wiki'),
       (4, 'Tag wiki excerpt'),
       (5, 'Tag wiki'),
       (6, 'Moderator nomination'),
       (7, 'Wiki placeholder'),
       (8, 'Privilege wiki'),
       (9, 'Article'),
       (10, 'HelpArticle'),
       (12, 'Collection'),
       (13, 'ModeratorQuestionnaireResponse'),
       (14, 'Announcement'),
       (15, 'CollectiveDiscussion'),
       (17, 'CollectiveCollection');

INSERT INTO "PostHistoryTypes" ("Id", "Name")
VALUES (1, 'Initial Title'),
       (2, 'Initial Body'),
       (3, 'Initial Tags'),
       (4, 'Edit Title'),
       (5, 'Edit Body'),
       (6, 'Edit Tags'),
       (7, 'Rollback Title'),
       (8, 'Rollback Body'),
       (9, 'Rollback Tags'),
       (10, 'Post Closed'),
       (11, 'Post Reopened'),
       (12, 'Post Deleted'),
       (13, 'Post Undeleted'),
       (14, 'Post Locked'),
       (15, 'Post Unlocked'),
       (16, 'Community Owned'),
       (17, 'Post Migrated'),
       (18, 'Question Merged'),
       (19, 'Question Protected'),
       (20, 'Question Unprotected'),
       (21, 'Post Disassociated'),
       (22, 'Question Unmerged'),
       (24, 'Suggested Edit Applied'),
       (25, 'Post Tweeted'),
       (31, 'Comment'),
       (33, 'Post notice added'),
       (34, 'Post notice removed'),
       (35, 'Post migrated away'),
       (36, 'Post migrated here'),
       (37, 'Post merge source'),
       (38, 'Post merge destination'),
       (50, 'Bumped by Community User'),
       (52, 'Question became hot network question (main) / Hot Meta question (meta)'),
       (53, 'Question removed from hot network/meta questions by a moderator'),
       (66, 'Created from Ask Wizard'),
       (23, 'Unknown dev related event'),
       (26, 'Vote nullification by dev (ERM?)'),
       (27, 'Post unmigrated/hidden moderator migration?'),
       (28, 'Unknown suggestion event'),
       (29, 'Unknown moderator event (possibly de-wikification?)'),
       (30, 'Unknown event (too rare to guess)');

INSERT INTO "VoteTypes" ("Id", "Name")
VALUES (-1, 'InformModerator'),
       (0, 'UndoMod'),
       (1, 'AcceptedByOriginator'),
       (2, 'UpMod (AKA upvote)'),
       (3, 'DownMod (AKA downvote)'),
       (4, 'Offensive'),
       (5, 'Favorite'),
       (6, 'Close'),
       (7, 'Reopen'),
       (8, 'BountyStart'),
       (9, 'BountyClose'),
       (10, 'Deletion'),
       (11, 'Undeletion'),
       (12, 'Spam'),
       (15, 'ModeratorReview'),
       (16, 'ApproveEditSuggestion'),
       (17, 'Reaction1 (Teams: celebrate)'),
       (18, 'Helpful'),
       (19, 'ThankYou (see Thank You reaction test)'),
       (20, 'WellWritten'),
       (21, 'Follow'),
       (22, 'Reaction2 (Teams: smile)'),
       (23, 'Reaction3 (Teams: mind blown)'),
       (24, 'Reaction4 (Teams: clap)'),
       (25, 'Reaction5 (Teams: heart)'),
       (26, 'Reaction6 (Teams: fire)'),
       (27, 'Reaction7 (Teams: trophy)'),
       (28, 'Reaction8 (Teams: wave)'),
       (29, 'Outdated (see Outdated Answers project)'),
       (30, 'NotOutdated'),
       (31, 'PreVote'),
       (32, 'CollectiveDiscussionUpvote'),
       (33, 'CollectiveDiscussionDownvote'),
       (35, 'privateAiAnswerCorrect'),
       (36, 'privateAiAnswerIncorrect'),
       (37, 'privateAiAnswerPartiallyCorrect');